IDSps1/Models/ErrorViewModel.cs
namespace IDSps1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IDSps1/Models/Review.cs
using System.ComponentModel.DataAnnotations;

namespace IDSps1.Models
{
    public class Review
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public string Requirements { get; set; }

        public string Link { get; set; }

        public Review()
        {

        }
    }
}

IDSps1/Models/charity.cs
using System.ComponentModel.DataAnnotations;

namespace IDSps1.Models
{
    public class Charity
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string NGO { get; set; }

        public string Requirements { get; set; }

        public Charity()
        {
            
        }
    }
}

IDSps1/Controllers/DonorController.cs
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Mvc;

namespace IDSps1.Controllers
{
    public class DonorController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DonorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Charity> objcharity = _db.Charity;
            return View(objcharity);
        }

        public IActionResult Payment()
        {
            return View();
        }
    }
}

IDSps1/Controllers/HomeController.cs
using IDSps1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IDSps1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IDSps1/Controllers/NGOController.cs
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Mvc;

namespace IDSps1.Controllers
{
    public class NGOController : Controller
    {
       
        private readonly ApplicationDbContext _db;

        public NGOController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Review> objReviews = _db.Reviews;
            return View(objReviews);
        }
        
    }
}

IDSps1/Controllers/charitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IDSps1.Data;
using IDSps1.Models;
using Microsoft.AspNetCore.Authorization;

namespace IDSps1.Controllers
{
    public class charitiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public charitiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: charities
        public async Task<IActionResult> Index()
        {
              return _context.Charity != null ? 
                          View(await _context.Charity.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.charity'  is null.");
        }

        // GET: charity/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();        
        }

        // POST: charity/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Charity.Where( j => j.NGO.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: charities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            return View(charity);
        }

        // GET: charities/Create
        
        public IActionResult Create()
        {
            return View();
        }

        // POST: charities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NGO,Requirements")] Charity charity)
        {
            if (ModelState.IsValid)
            {
                _context.Add(charity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(charity);
        }

        // GET: charities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity.FindAsync(id);
            if (charity == null)
            {
                return NotFound();
            }
            return View(charity);
        }

        // POST: charities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NGO,Requirements")] Charity charity)
        {
            if (id != charity.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(charity);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!charityExists(charity.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(charity);
        }

       

        // GET: charities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Charity == null)
            {
                return NotFound();
            }

            var charity = await _context.Charity
                .FirstOrDefaultAsync(m => m.Id == id);
            if (charity == null)
            {
                return NotFound();
            }

            return View(charity);
        }

        // POST: charities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Charity == null)
            {
                return Problem("Entity set 'ApplicationDbContext.charity'  is null.");
            }
            var charity = await _context.Charity.FindAsync(id);
            if (charity != null)
            {
                _context.Charity.Remove(charity);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool charityExists(int id)
        {
          return (_context.Charity?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IDSps1/Views/Donor/Index.cshtml
@model IEnumerable<IDSps1.Models.Charity>
@{
    ViewData["Title"] = "Index";
}

<h1>NGO List and Requirements</h1>
<table class="table table-bordered table-striped" style="width:100%">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                NGO
            </th>
            <th>
                Requirements
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                    @obj.Id
                </td>
                <td width="50%">
                    @obj.NGO
                </td>
                <td width="50%">
                    @obj.Requirements
                </td>
                <td>
                    <a asp-action="Payment" asp-route-id="@obj.Id">Donate</a> 
                </td>
            </tr>
        }
    </tbody>
</table>

IDSps1/Views/Donor/Payment.cshtml
@model Charity
@{
    ViewData["Title"] = "Payment";
}

<h1>Payment</h1>
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="test-primary">DONATION</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label>Amount</label>
            <input class="form-control" />
        </div>
        <div class="mb-3">
            <label>E-Signature</label>
            <input class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Proceed</button>
    </div>
</form>

IDSps1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">PS 1 CRUD Application</h1>
    <p>Learn about This is a Chairty Management Application useful for Donors and NGOs.</p>
</div>
 

IDSps1/Views/NGO/Index.cshtml
@model IDSps1.Models.Review

@{
    ViewData["Title"] = "Create";
}

<h1>Register New NGO</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirements" class="control-label"></label>
                <input asp-for="Requirements" class="form-control" />
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" style=padding: 50px; />
            </div>
        </form>
    </div>
</div>

IDSps1/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IDSps1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IDSps1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IDSps1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="charities" asp-action="Index">Charity</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Donor" asp-action="Index">Donate</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NGO" asp-action="Index">NGO</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - IDSps1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IDSps1/Views/charities/Create.cshtml
@model IDSps1.Models.Charity

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>charity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NGO" class="control-label"></label>
                <input asp-for="NGO" class="form-control" />
                <span asp-validation-for="NGO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirements" class="control-label"></label>
                <input asp-for="Requirements" class="form-control" />
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" style=padding: 50px; />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IDSps1/Views/charities/Delete.cshtml
@model IDSps1.Models.Charity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>charity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NGO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NGO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirements)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

IDSps1/Views/charities/Details.cshtml
@model IDSps1.Models.Charity

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>charity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NGO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NGO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirements)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirements)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

IDSps1/Views/charities/Edit.cshtml
@model IDSps1.Models.Charity

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>charity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NGO" class="control-label"></label>
                <input asp-for="NGO" class="form-control" />
                <span asp-validation-for="NGO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirements" class="control-label"></label>
                <input asp-for="Requirements" class="form-control" />
                <span asp-validation-for="Requirements" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" style=margin: 50px; />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IDSps1/Views/charities/Index.cshtml
@model IEnumerable<IDSps1.Models.Charity>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NGO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Requirements)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NGO)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Requirements)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

IDSps1/Views/charities/ShowSearchForm.cshtml
<h4>Search for Requirements</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
           
            
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
              
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>